DATASET:
  NAME: TripletData
  TRAIN_ROOT: dataset/triplet.csv
  TEST_ROOT: dataset/test_pairs.csv
  PRED_ROOT: dataset/test_lr_pairs.csv
  MATRIX_ROOT: dataset/exp_data_LR.csv
  ADJ_ROOT: dataset/spatial_graph.csv
MODEL:
  NAME: TripletGraphModel
  INPUT_DIM: 4000
  GRAPH_DIM: 4000
  MLP_HID_DIMS: [200,50,20]
  GRAPH_HID_DIMS: [200,50,20]
  SAVE_PATH: checkpoint/triplet/
TRAIN:
  LR: 0.000100
  EPOCHS: 10
  SAVE_PATH: checkpoint/triplet/
  BATCH_SIZE: 2048
TEST:
  SAVE_PATH: checkpoint/triplet/best_f1.pth
  BATCH_SIZE: 2048
  PRED: results/predict.csv
  EMB1: results/embed_ligand.csv
  EMB2: results/embed_receptor.csv
  THRESHOLD: 0.9
SEED: 10
use_cuda: cuda:0
