DATASET:
  NAME: "TripletData"
  TRAIN_ROOT: "dataset/cv2/triplet.csv"
  TEST_ROOT: "dataset/cv2/test_pairs.csv"
  MATRIX_ROOT: "dataset/exp_data_LR.csv"
  ADJ_ROOT: "dataset/adj_graph.csv"

MODEL:
  NAME: "TripletGraphModel"
  INPUT_DIM: 4000
  GRAPH_DIM: 4000
  MLP_HID_DIMS: [200, 60, 20]
  GRAPH_HID_DIMS: [200, 20, 5]
  SAVE_PATH: 'checkpoint/triplet/'

TRAIN:
  LR: 1e-4
  EPOCHS: 10
  SAVE_PATH: "checkpoint/triplet/"
  BATCH_SIZE: 512

TEST:
  SAVE_PATH: "checkpoint/triplet/final.pth"
  BATCH_SIZE: 512
  PRED: 'results/scadl_result.csv'
  THRESHOLD: 0.9

SEED: 10

PREPROSS:
  file_root: 'dataset/test_lr_pairs.csv'
  save_dir: 'dataset/cv2'
  split_threshold: 0.5
