DATASET:
  NAME: "TripletData"
  TRAIN_ROOT: "data_IO/triplet.csv"
  TEST_ROOT: "data_IO/test_pairs.csv"
  PRED_ROOT: "data_IO/test_lr_pairs.csv"
  MATRIX_ROOT: "data_IO/exp_data_LR.csv"
  ADJ_ROOT: "data_IO/spatial_graph.csv"

MODEL:
  NAME: "TripletGraphModel"
  INPUT_DIM: 3000
  GRAPH_DIM: 3000
  MLP_HID_DIMS: [200, 60, 30]
  GRAPH_HID_DIMS: [200, 60, 30]
  SAVE_PATH: 'checkpoint/triplet/'

TRAIN:
  LR: 1e-1
  EPOCHS: 200
  SAVE_PATH: "checkpoint/triplet/"
  BATCH_SIZE: 512

TEST:
  SAVE_PATH: "checkpoint/triplet/final.pth"
  BATCH_SIZE: 512
  PRED: 'results/predict.csv'
  EMB1: 'results/embed_ligand.csv'
  EMB2: 'results/embed_receptor.csv'
  THRESHOLD: 0.9

SEED: 10

